hol/urls.py
from django.urls import path
from . import views


app_name = "hol"
urlpatterns = [
    path("game_start/", views.new_game, name="new_game"),
    path("game/<str:game_id>/", views.game, name="game"),
    path("game/<str:game_id>/progress/", views.game_progress, name="game_progress"),
]

settings/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hol/', include("hol.urls")),
]

hol/models.py
from django.db import models
from django.utils import timezone
import uuid
import datetime


class YoutubeChannel(models.Model):
    channel_id = models.CharField(max_length=64, primary_key=True)
    uploads_id = models.CharField(max_length=64, unique=True)
    last_update = models.DateTimeField(default=timezone.now)
    title = models.CharField(max_length=128)
    views = models.IntegerField(default=0)
    subscribers = models.IntegerField(default=0)
    thumbnail = models.URLField(max_length=128)

    def __str__(self):
        return self.name

    def needs_update(self):
        return self.last_update < timezone.now() - datetime.timedelta(days=1)


class YoutubeVideo(models.Model):
    video_id = models.CharField(max_length=32, primary_key=True)
    channel = models.ForeignKey(YoutubeChannel, on_delete=models.CASCADE)
    title = models.CharField(max_length=128)
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.name


class Game(models.Model):
    # game_id is a seed for shuffle
    game_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    channel = models.ForeignKey(YoutubeChannel, on_delete=models.CASCADE)
    points = models.IntegerField(default=0)
    round = models.IntegerField(default=0)
    active = models.BooleanField(default=True)

    def __str__(self):
        return "Round: {}, Points: {}".format(self.round, self.points)

hol/forms.py
from django import forms


class NewGameForm(forms.Form):
    channel_id = forms.CharField(label="Youtube channel ID", max_length=32)

hol/views.py
from django.http.response import JsonResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.utils import timezone
from decouple import config
import random
import requests
from .forms import NewGameForm
from .models import Game, YoutubeChannel, YoutubeVideo

# UCrPseYLGpNygVi34QpGNqpA  - Ludwig
# UCNMyf6eTspYWPBm84VOqLkA  - shafter
# UCTwehlI2oqu3DXJ87Mu_99w  - me
# youtube data api v3
video_link = "https://www.googleapis.com/youtube/v3/videos?part=statistics&id={}&key={}"
channel_link = "https://www.googleapis.com/youtube/v3/channels?id={}&key={}&\
part=contentDetails,snippet,statistics"
ups_link = "https://www.googleapis.com/youtube/v3/playlistItems?playlistId={}&key={}\
&part=snippet&maxResults=50&pageToken={}"


def new_game(request):

    def fetch_channel_info(channel_id):
        try:
            res = requests.get(channel_link.format(channel_id, config("YT_PUBLIC_KEY"))).json()
            channel = res["items"][0]
            return {
                "uploads_id": channel["contentDetails"]["relatedPlaylists"]["uploads"],
                "thumbnail": channel["snippet"]["thumbnails"]["high"]["url"],
                "title": channel["snippet"]["title"],
                "subscriberCount": channel["statistics"]["subscriberCount"],
                "viewCount": channel["statistics"]["viewCount"],
            }
        except KeyError:
            return None

    def fetch_video_info(video_id):
        res = requests.get(video_link.format(video_id, config("YT_PUBLIC_KEY"))).json()
        return res["items"][0]

    def fetch_uploads(youtube_channel):
        page_token = ""
        key = config("YT_PUBLIC_KEY")
        uploads_id = youtube_channel.uploads_id

        while page_token is not None:
            res = requests.get(ups_link.format(uploads_id, key, page_token)).json()

            for upload in res["items"]:
                video_info = fetch_video_info(upload["snippet"]["resourceId"]["videoId"])
                try:
                    youtube_video = YoutubeVideo.objects.get(
                        video_id=upload["snippet"]["resourceId"]["videoId"])
                    youtube_video.title = upload["snippet"]["title"]
                    youtube_video.views = video_info["statistics"]["viewCount"]
                except YoutubeVideo.DoesNotExist:
                    YoutubeVideo.objects.create(
                        video_id=upload["snippet"]["resourceId"]["videoId"],
                        channel=youtube_channel,
                        title=upload["snippet"]["title"],
                        views=video_info["statistics"]["viewCount"]
                    )

            page_token = res.get("nextPageToken")

    def get_youtube_channel(channel_id):
        try:
            return YoutubeChannel.objects.get(channel_id=channel_id)
        except YoutubeChannel.DoesNotExist:
            return None

    if request.method == "POST":
        form = NewGameForm(request.POST)
        if form.is_valid():
            channel_id = form.cleaned_data["channel_id"]
            youtube_channel = get_youtube_channel(channel_id)

            if youtube_channel is None:
                channel_info = fetch_channel_info(channel_id)
                if channel_info is not None:
                    youtube_channel = YoutubeChannel(
                        channel_id=channel_id,
                        uploads_id=channel_info["uploads_id"],
                        title=channel_info["title"],
                        views=channel_info["viewCount"],
                        subscribers=channel_info["subscriberCount"],
                        thumbnail=channel_info["thumbnail"]
                    )
                    youtube_channel.save()
                    fetch_uploads(youtube_channel)
                else:
                    return render(request, "hol/newgame.html", {
                        "form": form,
                        "error_message": "Wrong channel id"
                    })
            elif youtube_channel.needs_update():
                youtube_channel.last_update = timezone.now()
                youtube_channel.save()
                fetch_uploads(youtube_channel)

            game = Game(channel=youtube_channel)
            game.save()

            return redirect("/hol/game/{}".format(game.game_id))

    form = NewGameForm()
    return render(request, "hol/newgame.html", {"form": form})


def game(request, game_id):
    if request.method == "GET":
        game = get_object_or_404(Game, pk=game_id)
        channel = game.channel
        videos = list(channel.youtubevideo_set.all())
        random.seed(game_id)
        random.shuffle(videos)

        vid_len = len(videos)
        index_1 = game.round % vid_len
        index_2 = (index_1 + 1) % vid_len

        return render(request, "hol/game.html", {
            "game": game,
            "channel": game.channel,
            "video_1": videos[index_1],
            "video_2": videos[index_2],
        })


def game_progress(request, game_id):

    def check_progress(video_1, video_2):
        if progress == "higher":
            if video_2.views >= video_1.views:
                return True
            else:
                return False
        else:  # lower
            if video_2.views <= video_1.views:
                return True
            else:
                return False

    if request.method == "POST":
        game = get_object_or_404(Game, pk=game_id)

        if not game.active:
            return JsonResponse({"result": "Game ended"})

        progress = request.POST.get("progress")
        videos = list(game.channel.youtubevideo_set.all())
        random.seed(game_id)
        random.shuffle(videos)

        vid_len = len(videos)
        index_1 = game.round % vid_len
        index_2 = (index_1 + 1) % vid_len

        video_1 = videos[index_1]
        video_2 = videos[index_2]

        if check_progress(video_1, video_2):
            game.round += 1
            game.points += 1
            game.save()

            video_1 = video_2
            video_2 = videos[(index_2 + 1) % vid_len]

            return JsonResponse({
                "result": "Correct",
                "points": game.points,
                "video_1": {
                    "video_id": video_1.video_id,
                    "title": video_1.title,
                    "views": video_1.views,
                },
                "video_2": {
                    "video_id": video_2.video_id,
                    "title": video_2.title,
                },
            })

        else:
            game.active = False
            game.save()

            return JsonResponse({
                "result": "Wrong",
                "video_2": {
                    "views": video_2.views
                },
            })

hol/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Base Template{% endblock title %}</title>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'hol/bootstrap.min.css' %}">

    {% block head %}{% endblock head %}
</head>

<body>
    {% block content %}{% endblock content %}
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
        integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
        integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous">
    </script>
</body>

</html>

hol/templates/hol/game.html
{% extends 'base.html' %}

{% block title %}Game{% endblock title %}

{% block head %}
<style>
    .base {
        background-color: #292929;
    }
</style>
{% endblock head %}

{% block content %}
<div class="container-fluid">
    <div class="row text-center mt-3">
        <div class="mx-auto" style="max-height: 200px; max-width: 200px;">
            <img src="{{ channel.thumbnail }}" alt="Channel thumbnail" class="rounded img-fluid">
        </div>
        <h2>{{ channel.title }}</h2>
        <p class="mb-2">Subs: {{ channel.subscribers }}</p>
        <h2 id="game_points">{{ game.points }}</h2>
    </div>
    <div class="row">
        <div class="col text-center base pt-3">
            <img id="v1_img" src="https://img.youtube.com/vi/{{ video_1.video_id }}/hqdefault.jpg" alt="Video thumbnail"
                class="rounded mx-auto d-block img-fluid">
            <p id="v1_title"> {{ video_1.title }} </p>
            <p id="v1_views"> Views: {{ video_1.views }} </p>
        </div>
        <div class="col text-center base pt-3">
            <img id="v2_img" src="https://img.youtube.com/vi/{{ video_2.video_id }}/hqdefault.jpg" alt="Video thumbnail"
                class="rounded mx-auto d-block img-fluid">
            <p id="v2_title"> {{ video_2.title }} </p>
            <p id="v2_views">
                {% if game.active %}
                Hidden
                {% else %}
                Views: {{ video_2.views }}
                {% endif %}
            </p>
            <button id="higher" class="game_button btn btn-primary">Higher</button>
            <button id="lower" class="game_button btn btn-primary">Lower</button>
            <p id="result"></p>
        </div>
    </div>
</div>

{% if game.active %}
<input type="hidden" id="game_progress" value="none">
{% else %}
<input type="hidden" id="game_progress" value="lose">
{% endif %}

{% csrf_token %}
<script>
    $(".game_button").click(function (event) {
        current_result = $("#game_progress").val()
        if (current_result == "Correct" || current_result == "none") {
            $.ajax({
                url: "{% url 'hol:game_progress' game.game_id %}",
                headers: {
                    "X-CSRFToken": $("[name=csrfmiddlewaretoken]").val()
                },
                method: "POST",
                data: {
                    "progress": event.target.id
                },
                success: function (data) {
                    result = data["result"]
                    if (result == "Correct") {
                        $("#v1_img").attr("src", "https://img.youtube.com/vi/" + data["video_1"][
                            "video_id"
                        ] + "/hqdefault.jpg");
                        $("#v1_title").html(data["video_1"]["title"]);
                        $("#v1_views").html("Views: " + data["video_1"]["views"]);
                        $("#v2_img").attr("src", "https://img.youtube.com/vi/" + data["video_2"][
                            "video_id"
                        ] + "/hqdefault.jpg");
                        $("#v2_title").html(data["video_2"]["title"]);
                        $("#game_points").html(data["points"]);
                    } else if (result == "Wrong") {
                        $("#v2_views").html("Views: " + data["video_2"]["views"]);
                    }
                    $("#result").html(result);
                    $("#game_progress").val(result);
                }
            });
        }
    });
</script>
{% endblock content %}

hol/templates/hol/newgame.html
{% extends 'base.html' %}

{% block title %}Create New Game{% endblock title %}

{% block head %}
<style>
    .base {
        background-color: #292929;
    }
</style>
{% endblock head %}

{% block content %}
<div class="container base">
    <form method="post" class="mt-3 pe-2 pt-3 pb-3">
        {% csrf_token %}
        <div class="mb-3">
            {% if error_message %}
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                {{ error_message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {% endif %}
            <label for="id_channel_id" class="form-label">Youtube channel ID:</label>
            <input type="text" name="channel_id" maxlength="32" required="" id="id_channel_id" class="form-control">
            <div id="channelHelp" class="form-text">Must be ID, not username</div>
        </div>
        <input type="submit" value="Create" class="btn btn-primary w-100">
    </form>
</div>
{% endblock content %}